# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='established_date',
            field=models.DateField(verbose_name='Establishment Date'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='appointed_date',
            field=models.DateField(verbose_name='appointed date'),
        ),
    ]
