# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190219_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='remarks',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default='Not provided', max_length=500),
        ),
        migrations.AddField(
            model_name='school',
            name='principal',
            field=models.CharField(default='Not provided', max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Not provided', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='domain',
            field=models.CharField(default='Not provided', max_length=300),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True),
        ),
    ]
